# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  instagram_client_id: a2c3c6f198b542e380eec280067f4cf5
  instagram_client_secret: 91747c2929034e20a644ed80c839b0fa
  secret_key_base: e9c4a78895efde51a0c97561a69884a16e57bff632f6566aa21d0c8804dc80742b630b35ecb1a70d0268334e9c88d8873ef4a7ee6a4cfbfa5ebc636eaf556592

test:
  secret_key_base: c81565eaa60a94b7bcbf1bca957584dfc90c20d93319be8965e790c3617edcd1c86240a06eb90099960975ec3b14d7f2a8b1f3f3f916c198b33e567322d1008c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
